services:
  web:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "mkary_1992"
      POSTGRES_DB: "stc_assessment"
      POSTGRES_USER: "root"
      PGUSER: "root"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080